apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
      annotations:
        rollme: "time-{{now | unixEpoch}}"
    spec:
      containers:
        - name: django
          image: ritika5993/djangoapp:$CODEBUILD_RESOLVED_SOURCE_VERSION
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
