apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
      annotations:
        rollme: "time-{{now | unixEpoch}}"  # This forces Kubernetes to restart the deployment
    spec:
      containers:
        - name: django
          image: ritika5993/djangoapp:${{ github.sha }}  # Ensure this tag is unique (commit SHA)
          imagePullPolicy: Always
          ports:
            - containerPort: 8000

